"""XP3 CxEncryption — bytecode VM-based encryption used by KiriKiri TPM plugins.

This implements the CxEncryption system used by many KiriKiri games (YuzuSoft,
Nanawind, and others). The encryption uses a bytecode virtual machine that
generates per-file XOR programs from a control block extracted from the game's
TPM plugin.

The algorithm:
1. Split the file at a threshold offset: ``(hash & mask) + offset``
2. Before the threshold, derive keys from ``hash``
3. After the threshold, derive keys from ``(hash >> 16) ^ hash``
4. Key derivation runs the bytecode VM twice (with ``hash >> 7`` and ``~(hash >> 7)``)
   and extracts XOR key bytes from the results

Based on GARbro's CxEncryption implementation (KiriKiriCx.cs, YuzCrypt.cs).
"""

from __future__ import annotations

import struct

from .base import XP3Encryption

U32_MASK = 0xFFFFFFFF


def _u32(val):
    """Truncate to unsigned 32-bit."""
    return val & U32_MASK


def _rotl(val, n):
    """32-bit rotate left."""
    val &= U32_MASK
    n &= 31
    return _u32((val << n) | (val >> (32 - n)))


def _rotr(val, n):
    """32-bit rotate right."""
    val &= U32_MASK
    n &= 31
    return _u32((val >> n) | (val << (32 - n)))


# ---------------------------------------------------------------------------
# Bytecode VM
# ---------------------------------------------------------------------------


class CxProgram:
    """Bytecode program generated by CxEncryption for a specific seed.

    Each unique ``hash & 0x7F`` value produces a different program. The program
    is a list of (opcode, operand) tuples interpreted by :meth:`execute`.
    """

    LENGTH_LIMIT = 0x80

    # Opcodes that consume an immediate value from the next code entry.
    _IMMED_OPCODES = frozenset(
        {
            "ADD_EAX_IMM",
            "SUB_EAX_IMM",
            "AND_EBX_IMM",
            "AND_EAX_IMM",
            "XOR_EAX_IMM",
            "MOV_EAX_IMM",
        }
    )

    def __init__(self, seed, control_block, random_fn=None):
        self._seed = seed
        self._control_block = control_block
        self._random_fn = random_fn or self._default_random
        self._code = []  # flat list of opcodes/immediates
        self._length = 0

    # -- PRNG variants -------------------------------------------------------

    def _default_random(self):
        """Standard LCG PRNG (CxProgram)."""
        old = self._seed
        self._seed = _u32(1103515245 * self._seed + 12345)
        return _u32(self._seed ^ _u32(old << 16) ^ _u32(old >> 16))

    def get_random(self):
        return self._random_fn()

    # -- Code emission -------------------------------------------------------

    def clear(self):
        self._code.clear()
        self._length = 0

    def emit_nop(self, count):
        if self._length + count > self.LENGTH_LIMIT:
            return False
        self._length += count
        return True

    def emit(self, opcode, length=1):
        if self._length + length > self.LENGTH_LIMIT:
            return False
        self._length += length
        self._code.append(opcode)
        return True

    def emit_u32(self, value):
        if self._length + 4 > self.LENGTH_LIMIT:
            return False
        self._length += 4
        self._code.append(_u32(value))
        return True

    def emit_random(self):
        return self.emit_u32(self.get_random())

    # -- Execution -----------------------------------------------------------

    def execute(self, hash_val):
        eax = ebx = ecx = edi = _u32(0)
        stack = []
        it = iter(self._code)

        for entry in it:
            # If the entry is an integer, skip (stale immediate — shouldn't happen).
            if isinstance(entry, int):
                continue

            opcode = entry

            # Instructions that consume an immediate: read the next entry first.
            imm = 0
            if opcode in self._IMMED_OPCODES:
                imm = next(it)

            if opcode == "NOP":
                continue
            elif opcode == "MOV_EDI_ARG":
                edi = _u32(hash_val)
            elif opcode == "PUSH_EBX":
                stack.append(ebx)
            elif opcode == "POP_EBX":
                ebx = stack.pop()
            elif opcode == "PUSH_ECX":
                stack.append(ecx)
            elif opcode == "POP_ECX":
                ecx = stack.pop()
            elif opcode == "MOV_EBX_EAX":
                ebx = eax
            elif opcode == "MOV_EAX_EDI":
                eax = edi
            elif opcode == "MOV_ECX_EBX":
                ecx = ebx
            elif opcode == "MOV_EAX_EBX":
                eax = ebx
            elif opcode == "AND_ECX_0F":
                ecx = ecx & 0x0F
            elif opcode == "SHR_EBX_1":
                ebx = ebx >> 1
            elif opcode == "SHL_EAX_1":
                eax = _u32(eax << 1)
            elif opcode == "SHR_EAX_CL":
                eax = _u32(eax >> (ecx & 0x1F))
            elif opcode == "SHL_EAX_CL":
                eax = _u32(eax << (ecx & 0x1F))
            elif opcode == "OR_EAX_EBX":
                eax = eax | ebx
            elif opcode == "NOT_EAX":
                eax = _u32(~eax)
            elif opcode == "NEG_EAX":
                eax = _u32(-eax)
            elif opcode == "DEC_EAX":
                eax = _u32(eax - 1)
            elif opcode == "INC_EAX":
                eax = _u32(eax + 1)
            elif opcode == "ADD_EAX_EBX":
                eax = _u32(eax + ebx)
            elif opcode == "SUB_EAX_EBX":
                eax = _u32(eax - ebx)
            elif opcode == "IMUL_EAX_EBX":
                eax = _u32(eax * ebx)
            elif opcode == "ADD_EAX_IMM":
                eax = _u32(eax + imm)
            elif opcode == "SUB_EAX_IMM":
                eax = _u32(eax - imm)
            elif opcode == "AND_EBX_IMM":
                ebx = ebx & imm
            elif opcode == "AND_EAX_IMM":
                eax = eax & imm
            elif opcode == "XOR_EAX_IMM":
                eax = eax ^ imm
            elif opcode == "MOV_EAX_IMM":
                eax = imm
            elif opcode == "MOV_EAX_INDIRECT":
                if eax >= len(self._control_block):
                    raise RuntimeError(
                        f"CxProgram: index {eax} out of bounds (control block size {len(self._control_block)})"
                    )
                eax = _u32(~self._control_block[eax])
            elif opcode == "RETN":
                if stack:
                    raise RuntimeError("CxProgram: imbalanced stack at RETN")
                return eax
            else:
                raise RuntimeError(f"CxProgram: unknown opcode {opcode!r}")

        raise RuntimeError("CxProgram: no RETN")


# ---------------------------------------------------------------------------
# Code generator
# ---------------------------------------------------------------------------


class CxCodeGenerator:
    """Generates CxProgram bytecode using the CxEncryption algorithm."""

    def __init__(self, control_block, prolog_order, odd_branch_order, even_branch_order, prng_factory=None):
        self._control_block = control_block
        self._prolog_order = prolog_order
        self._odd_branch_order = odd_branch_order
        self._even_branch_order = even_branch_order
        self._prng_factory = prng_factory

    def generate(self, seed):
        """Generate a CxProgram for the given seed (hash & 0x7F).

        The program object is created once and reused across stage attempts.
        When a stage fails (program too large), the code is cleared but the
        PRNG state carries forward — matching the TPM's behavior.
        """
        program = CxProgram(seed, self._control_block, self._prng_factory(seed) if self._prng_factory else None)
        for stage in range(5, 0, -1):
            if self._emit_code(program, stage):
                return program
            program.clear()
        raise RuntimeError("CxEncryption: overly large bytecode")

    def _emit_code(self, p, stage):
        return (
            p.emit_nop(5)
            and p.emit("MOV_EDI_ARG", 4)
            and self._emit_body(p, stage)
            and p.emit_nop(5)
            and p.emit("RETN")
        )

    def _emit_body(self, p, stage):
        if stage == 1:
            return self._emit_prolog(p)

        if not p.emit("PUSH_EBX"):
            return False

        if p.get_random() & 1:
            ok = self._emit_body(p, stage - 1)
        else:
            ok = self._emit_body2(p, stage - 1)
        if not ok:
            return False

        if not p.emit("MOV_EBX_EAX", 2):
            return False

        if p.get_random() & 1:
            ok = self._emit_body(p, stage - 1)
        else:
            ok = self._emit_body2(p, stage - 1)
        if not ok:
            return False

        return self._emit_odd_branch(p) and p.emit("POP_EBX")

    def _emit_body2(self, p, stage):
        if stage == 1:
            return self._emit_prolog(p)

        if p.get_random() & 1:
            ok = self._emit_body(p, stage - 1)
        else:
            ok = self._emit_body2(p, stage - 1)
        if not ok:
            return False

        return self._emit_even_branch(p)

    def _emit_prolog(self, p):
        choice = self._prolog_order[p.get_random() % 3]
        if choice == 2:
            return (
                p.emit_nop(5)
                and p.emit("MOV_EAX_IMM", 2)
                and p.emit_u32(p.get_random() & 0x3FF)
                and p.emit("MOV_EAX_INDIRECT", 0)
            )
        elif choice == 1:
            return p.emit("MOV_EAX_EDI", 2)
        elif choice == 0:
            return p.emit("MOV_EAX_IMM") and p.emit_random()
        return False

    def _emit_even_branch(self, p):
        choice = self._even_branch_order[p.get_random() & 7]
        if choice == 0:
            return p.emit("NOT_EAX", 2)
        elif choice == 1:
            return p.emit("DEC_EAX")
        elif choice == 2:
            return p.emit("NEG_EAX", 2)
        elif choice == 3:
            return p.emit("INC_EAX")
        elif choice == 4:
            return p.emit_nop(5) and p.emit("AND_EAX_IMM") and p.emit_u32(0x3FF) and p.emit("MOV_EAX_INDIRECT", 3)
        elif choice == 5:
            return (
                p.emit("PUSH_EBX")
                and p.emit("MOV_EBX_EAX", 2)
                and p.emit("AND_EBX_IMM", 2)
                and p.emit_u32(0xAAAAAAAA)
                and p.emit("AND_EAX_IMM")
                and p.emit_u32(0x55555555)
                and p.emit("SHR_EBX_1", 2)
                and p.emit("SHL_EAX_1", 2)
                and p.emit("OR_EAX_EBX", 2)
                and p.emit("POP_EBX")
            )
        elif choice == 6:
            return p.emit("XOR_EAX_IMM") and p.emit_random()
        elif choice == 7:
            if p.get_random() & 1:
                ok = p.emit("ADD_EAX_IMM")
            else:
                ok = p.emit("SUB_EAX_IMM")
            return ok and p.emit_random()
        return False

    def _emit_odd_branch(self, p):
        choice = self._odd_branch_order[p.get_random() % 6]
        if choice == 0:
            return (
                p.emit("PUSH_ECX")
                and p.emit("MOV_ECX_EBX", 2)
                and p.emit("AND_ECX_0F", 3)
                and p.emit("SHR_EAX_CL", 2)
                and p.emit("POP_ECX")
            )
        elif choice == 1:
            return (
                p.emit("PUSH_ECX")
                and p.emit("MOV_ECX_EBX", 2)
                and p.emit("AND_ECX_0F", 3)
                and p.emit("SHL_EAX_CL", 2)
                and p.emit("POP_ECX")
            )
        elif choice == 2:
            return p.emit("ADD_EAX_EBX", 2)
        elif choice == 3:
            return p.emit("NEG_EAX", 2) and p.emit("ADD_EAX_EBX", 2)
        elif choice == 4:
            return p.emit("IMUL_EAX_EBX", 3)
        elif choice == 5:
            return p.emit("SUB_EAX_EBX", 2)
        return False


# ---------------------------------------------------------------------------
# PRNG factories
# ---------------------------------------------------------------------------


def make_lcg_prng(seed):
    """Create a standard LCG PRNG closure for CxProgram."""
    state = [seed]

    def prng():
        old = state[0]
        state[0] = _u32(1103515245 * state[0] + 12345)
        return _u32(state[0] ^ _u32(old << 16) ^ _u32(old >> 16))

    return prng


def make_nana_prng(seed, random_seed):
    """Create a CxProgramNana xorshift PRNG closure for CxProgram.

    Used by CabbageCxCrypt / NanaCxCrypt / RiddleCxCrypt (YuzuSoft-family).
    """
    state = [seed, random_seed]

    def prng():
        s = _u32(state[0] ^ _u32(state[0] << 17))
        s = _u32(s ^ (_u32(s << 18) | (s >> 15)))
        state[0] = _u32(~s)
        r = _u32(state[1] ^ _u32(state[1] << 13))
        r = r ^ (r >> 17)
        state[1] = _u32(r ^ _u32(r << 5))
        return _u32(state[0] ^ state[1])

    return prng


# ---------------------------------------------------------------------------
# Control block extraction
# ---------------------------------------------------------------------------

CONTROL_BLOCK_SIGNATURE = b" Encryption control block"
CONTROL_BLOCK_SIZE = 0x400  # 1024 uint32 values


def extract_control_block(tpm_data):
    """Extract and invert the control block from a TPM plugin binary.

    Returns a list of 1024 uint32 values, or None if the signature is not found.
    """
    idx = tpm_data.find(CONTROL_BLOCK_SIGNATURE)
    if idx < 0:
        return None
    raw = struct.unpack_from(f"<{CONTROL_BLOCK_SIZE}I", tpm_data, idx)
    return [_u32(~v) for v in raw]


# ---------------------------------------------------------------------------
# CxEncryption handler
# ---------------------------------------------------------------------------


class CxEncryption(XP3Encryption):
    """CxEncryption-based XP3 decryption.

    The control block can be provided directly or loaded from a TPM file.
    When ``tpm_file`` is given, the control block is extracted automatically
    using :func:`extract_control_block`.

    Args:
        control_block: List of 1024 uint32 values (inverted from TPM).
            Mutually exclusive with ``tpm_file``.
        tpm_file: Path to a TPM plugin file to extract the control block from.
            Mutually exclusive with ``control_block``.
        mask: Threshold mask for the hash-based offset split.
        offset: Threshold offset added to the masked hash.
        prolog_order: 3-element permutation of [0, 1, 2].
        odd_branch_order: 6-element permutation of [0, 1, 2, 3, 4, 5].
        even_branch_order: 8-element permutation of [0, 1, 2, 3, 4, 5, 6, 7].
        prng_type: ``"lcg"`` for standard or ``"nana"`` for CxProgramNana.
        random_seed: Extra seed for the ``"nana"`` PRNG variant.
    """

    def __init__(
        self,
        control_block=None,
        mask=0,
        offset=0,
        prolog_order=None,
        odd_branch_order=None,
        even_branch_order=None,
        prng_type="lcg",
        random_seed=0,
        tpm_file=None,
    ):
        if control_block is None and tpm_file is None:
            raise ValueError("Either control_block or tpm_file must be provided")
        if control_block is None:
            with open(tpm_file, "rb") as f:
                tpm_data = f.read()
            control_block = extract_control_block(tpm_data)
            if control_block is None:
                raise ValueError(f"No control block signature found in {tpm_file}")

        self._control_block = list(control_block)
        self._mask = mask
        self._offset = offset
        self._prolog_order = prolog_order or [0, 1, 2]
        self._odd_branch_order = odd_branch_order or [0, 1, 2, 3, 4, 5]
        self._even_branch_order = even_branch_order or [0, 1, 2, 3, 4, 5, 6, 7]
        self._prng_type = prng_type
        self._random_seed = random_seed

        if prng_type == "nana":
            self._prng_factory = lambda seed: make_nana_prng(seed, random_seed)
        else:
            self._prng_factory = None  # uses default LCG

        self._codegen = CxCodeGenerator(
            self._control_block,
            self._prolog_order,
            self._odd_branch_order,
            self._even_branch_order,
            self._prng_factory,
        )
        self._program_cache = {}

    def _get_program(self, seed):
        if seed not in self._program_cache:
            self._program_cache[seed] = self._codegen.generate(seed)
        return self._program_cache[seed]

    def _execute_xcode(self, hash_val):
        seed = hash_val & 0x7F
        program = self._get_program(seed)
        h = hash_val >> 7
        ret1 = program.execute(_u32(h))
        ret2 = program.execute(_u32(~h))
        return ret1, ret2

    def _decode(self, buf, key, file_offset):
        """Apply CxEncryption XOR to buffer bytes."""
        ret1, ret2 = self._execute_xcode(key)
        key1 = (ret2 >> 16) & 0xFFFF
        key2 = ret2 & 0xFFFF
        key3 = ret1 & 0xFF
        if key1 == key2:
            key2 = _u32(key2 + 1)
        if key3 == 0:
            key3 = 1

        # Bulk XOR with key3 (point XORs at pos1/pos2 commute with it)
        result = bytearray(buf.translate(bytes(i ^ key3 for i in range(256))))

        # Point XOR at specific offsets
        pos2 = key2 - file_offset
        if 0 <= pos2 < len(result):
            result[pos2] ^= (ret1 >> 16) & 0xFF

        pos1 = key1 - file_offset
        if 0 <= pos1 < len(result):
            result[pos1] ^= (ret1 >> 8) & 0xFF

        return bytes(result)

    def _get_base_offset(self, hash_val):
        return _u32((hash_val & self._mask) + self._offset)

    def _apply(self, data, info, segment):
        """Decrypt or encrypt (symmetric XOR).

        The file_offset is always 0 because XP3 segments are decrypted
        independently starting from the beginning of each segment's data.
        The segment.offset field is the archive-level byte position, not
        the file-local offset used by CxEncryption's threshold split.
        """
        hash_val = _u32(info.key)
        base_offset = self._get_base_offset(hash_val)
        file_offset = 0

        buf = bytearray(data)
        pos = 0

        if file_offset < base_offset:
            base_length = min(base_offset - file_offset, len(buf))
            chunk = self._decode(bytes(buf[:base_length]), hash_val, file_offset)
            buf[:base_length] = chunk
            file_offset += base_length
            pos = base_length

        if pos < len(buf):
            transformed_key = _u32((hash_val >> 16) ^ hash_val)
            chunk = self._decode(bytes(buf[pos:]), transformed_key, file_offset)
            buf[pos:] = chunk

        return bytes(buf)

    def decrypt(self, data, info, segment):
        return self._apply(data, info, segment)

    def encrypt(self, data, info, segment):
        return self._apply(data, info, segment)
